# Generated by Django 4.2 on 2024-08-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cnt",
            field=models.IntegerField(default=0),
        ),
    ]
