# Generated by Django 4.2 on 2024-08-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_hashtag_product_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True, default="images/product1.jpg", upload_to="images/"
            ),
        ),
    ]
