# Generated by Django 4.2 on 2024-08-22 13:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_index_photo_index_uuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Product',
        ),
    ]
